# Generated by Django 5.1.1 on 2024-10-16 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('standard', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(upload_to='student_photos/')),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training_images/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_images', to='api.student')),
            ],
        ),
    ]
